In [22]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [7]:
df = pd.read_csv('citrus.csv')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [9]:
df.head(1000)

name  diameter  weight  red  green  blue
0    orange      2.96   86.76  172     85     2
1    orange      3.91   88.05  166     78     3
2    orange      4.42   95.17  156     81     2
3    orange      4.47   95.60  163     81     4
4    orange      4.48   95.76  161     72     9
..      ...       ...     ...  ...    ...   ...
995  orange      7.43  137.10  158     78     3
996  orange      7.44  137.12  164     97     2
997  orange      7.44  137.18  140     88     2
998  orange      7.44  137.23  148     85     2
999  orange      7.44  137.24  166     83     7

[1000 rows x 6 columns]

In [10]:
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [11]:
dataset = df.values
print(dataset)

[[0 2.96 86.76 172 85 2]
 [0 3.91 88.05 166 78 3]
 [0 4.42 95.17 156 81 2]
 ...
 [1 15.59 256.5 168 82 20]
 [1 15.92 260.14 142 72 11]
 [1 16.45 261.51 152 74 2]]


In [14]:
# memberikan atribut dan label

x = dataset[:, 1:6]  # atribut
y = dataset[:, 0]    # label

print(x)
print()
print(y)

[[2.96 86.76 172 85 2]
 [3.91 88.05 166 78 3]
 [4.42 95.17 156 81 2]
 ...
 [15.59 256.5 168 82 20]
 [15.92 260.14 142 72 11]
 [16.45 261.51 152 74 2]]

[0 0 0 ... 1 1 1]


In [17]:
# Normalisasi
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(x)
X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

In [21]:
Y_train = Y_train.astype(np.float32)
Y_test = Y_test.astype(np.float32)

In [23]:
model = Sequential([Dense(32, activation='relu', input_shape=(5,)),
                    Dense(32, activation='relu'),
                    Dense(1, activation='sigmoid')])

In [25]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [26]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
219/219 [==============================] - 15s 1ms/step - loss: 0.7042 - accuracy: 0.5305
Epoch 2/100
219/219 [==============================] - 0s 1ms/step - loss: 0.6415 - accuracy: 0.8505
Epoch 3/100
219/219 [==============================] - 0s 1ms/step - loss: 0.5913 - accuracy: 0.8851
Epoch 4/100
219/219 [==============================] - 0s 1ms/step - loss: 0.5231 - accuracy: 0.9003
Epoch 5/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4342 - accuracy: 0.9216
Epoch 6/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.9201
Epoch 7/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2869 - accuracy: 0.9281
Epoch 8/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2445 - accuracy: 0.9272
Epoch 9/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2249 - accuracy: 0.9250
Epoch 10/100
219/219 [==============================] - 0s 1ms/step - loss: 0.2042 - accur

In [27]:
model.evaluate(X_test, Y_test)

94/94 [==============================] - 1s 937us/step - loss: 0.1867 - accuracy: 0.9190


[0.1867029368877411, 0.9190000295639038]